root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -mod=vendor -o ./tmp/main ./cmd/faucet/main.go"
  bin = "./tmp/main"
  include_dir = ["cmd", "internal", "web"]
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  exclude_dir = ["assets", "tmp", "vendor"]
  delay = 1000 # ms